load("@rules_python//python:defs.bzl", "py_test")

py_test(
    name = "test_shared_lib",
    size = "small",
    srcs = [
        "__init__.py",
        "conftest.py",
        "run_pytest.py",
        "test_shared_lib.py",
    ],
    data = [
        "//ground_control:pytest.ini",
        "//onboard:libonboard.so",
    ],
    main = "run_pytest.py",
    deps = [
        "//ground_control:onboard_client",
        "@pypi//pytest",
    ],
)
