load("@rules_python//python:defs.bzl", "py_binary", "py_library")

py_library(
    name = "onboard_client",
    srcs = [
        "onboard/__init__.py",
        "onboard/client.py",
    ],
    visibility = ["//visibility:public"],
    deps = [],
)

py_library(
    name = "ground_control_lib",
    srcs = ["__init__.py"],
    visibility = ["//visibility:public"],
    deps = [":onboard_client"],
)

py_binary(
    name = "ground_control",
    srcs = ["main.py"],
    data = ["//onboard:libonboard.so"],
    main = "main.py",
    deps = [":ground_control_lib"],
)
